### ISSUE TITLE
No build logs on macOS in /var/pkg_comp/log/

### ISSUE THREAD

**Issue by jlmuir** [jmmv/pkg_comp#12] opened 2017-03-22 15:14 UTC
On macOS Sierra 10.12.3, I followed the [Easy pkgsrc on macOS with pkg_comp 2.0](http://julio.meroh.net/2017/02/pkg_comp-2.0-tutorial-macos.html) tutorial (using `pkg_comp-2.0-20170223-macos.pkg`) and then ran an auto build (as root):

```
# pkg_comp auto
```

(Just in case it matters, I actually ran two shorter auto builds before this where I listed a few packages on the command line after the `auto` subcommand just to test that it works.)

It attempted to build 485 packages (some of which succeeded and some of which failed), and seemed to run OK and exited with an exit status of 0.  However, when I went to review the build logs, I found that there were none:

```
% ls -alF /var/pkg_comp/log/
total 0
drwxr-xr-x  2 root  wheel   68 Feb 23 16:05 ./
drwxr-xr-x  7 root  wheel  238 Mar 22 04:59 ../
```

**Comment by jmmv** [comment] 2017-03-23 20:02
This is actually working as intended: `/var/pkg_comp/log/` only contains logs for automated runs via `pkg_comp4cron`.

I agree logging could be better in any case (particularly because it's now pretty much impossible to access logs for build failures), and I think issues #3 and #7 already contain enough details about this and proper tracking. Will close this. Poke those issues if you have further comments please.

**Closed by jmmv** 2017-03-23 20:02 UTC
